apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: neuvectorusagerecords.neuvector.com
spec:
  group: neuvector.com
  names:
    kind: NeuvectorUsageRecord
    listKind: NeuvectorUsageRecordList
    plural: neuvectorusagerecords
    singular: neuvectorusagerecord
    shortNames:
    - nur
  scope: Cluster
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          managed_node_count:
            type: integer
          reporting_time:
            type: string
        required:
          - managed_node_count
          - reporting_time
        type: object
    served: true
    storage: true
